title: EasyStatisticsAcademy
description: Learn statistics in a clear, practical way with SPSS, R, Python, and Excel.
url: "https://easystatisticsacademy.com"
timezone: UTC
markdown: kramdown
permalink: pretty